# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.14.2'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm build
    displayName: >
      npm install and build

  - script: |
      npm test
    displayName: >
      npm test







